name: Build Debian Package
on: push
jobs:
  release:
   runs-on: ubuntu-20.04
   steps:
   - name: Checkout Master
     uses: actions/checkout@v2
     
   - name: Build Debian package
     uses: dawidd6/action-debian-package@v1
     with:
       artifacts_directory: output
   
   - name: Build RPM package
     id: rpm
     uses: bunsenmurder/rpmbuild@v2.0.9
     with:
       spec_file: "nosurfin.spec"
       
   - uses: actions/upload-artifact@v2
     with:
       name: NoSurfin DEB
       path: /home/runner/work/nosurfin/nosurfin/output
       
   - uses: actions/upload-artifact@v2
     with:
       name: NoSurfin RPM
       path: ${{ steps.rpm.outputs.rpm_dir_path }}
